services:
  - type: web
    name: aagni-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        fromDotEnv: true
      - key: GEMINI_API_KEY
        fromDotEnv: true
