services:
  - type: web
    name: aagni-bot
    runtime: python
    repo: https://github.com/Kansal0920/aagni-assistant
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: GEMINI_API_KEY
        sync: false
    region: oregon
    plan: free
